### ISSUE TITLE
About test

### ISSUE THREAD

**Issue by yangjob** [hyperplane-lab/Generative-3D-Part-Assembly#9]
Hi, good job.  Could you please tell me how to get the result during testing. And the I train the model successfully, but it seems that the trained network model is not suitable for the tested model. thanks.

**Comment by Championchess** [comment]
Hello! You could use the blender to render the 3d point cloud to obtain the visualization results as presented in the paper.
Could you please have a more detailed discription about the not-matching phenomena? thanks

**Comment by Championchess** [comment]
Recently a person asked me about a mismatching problem of the trained model and the testing process. Maybe the reason is that you didn't delete "iter = 7" in the train_dynamic.sh. The default value for iteration number is 5, not 7, which is adapted in test_dynamics.sh. Different iteration numbers make different models, so you encounter the problem of not matching. I have just deleted the "iter = 7" and updated the train_dynamics.sh file. You can use the new version of code now. Thanks for your comment.
